version: '2.2'

services:
  portainer:
    image: portainer/portainer
    container_name: "portainer"
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainerdata:/data
  rabbit:
    image: rabbitmq:3-management
    container_name: "message-queue"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: retaildemo
      RABBITMQ_DEFAULT_PASS : password
 
networks:
  default:
    name: retail-demo
    driver: bridge