version: '3.4'

services:
  store-web:
    image: ${DOCKER_REGISTRY}storeweb
    build:
      context: .
      dockerfile: store-web/Dockerfile
    environment:
      servicebus_connection_string: ${servicebus_connection_string-host=message-queue; username=retaildemo; password=password}

networks:
  default:
    external:
      name: retail-demo